### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by UnknownNull** [hachkingtohach1/ReallyCheat#19]
[04:15:16.920] [Server thread/INFO]: [NetworkSession: 127.0.0.1 55643] Session opened
[04:15:16.920] [Server thread/INFO]: [NetworkSession: 127.0.0.1 55643] Player: AREF
[04:15:16.920] [Server thread/CRITICAL]: ErrorException: "scandir(C:\Users\Administrator\Documents\2.survival\plugins\/ReallyCheat/src/hachkingtohach1/reallycheat/checks/network): The system cannot find the path specifi (code: 3)" (EXCEPTION) in "plugins/ReallyCheat-master/src/hachkingtohach1/reallycheat/utils/Utils" at line 40
--- Stack trace ---
  #0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[171] scandir(C:\Users\Administrator\Documents\2.survival\plugins\/ReallyCheat/src/hac, string[118] C:\Users\Administrator\Documents\2.survival\plugins\ReallyCheat-master\src\hachk, int 40)
  #1 plugins/ReallyCheat-master/src/hachkingtohach1/reallycheat/utils/Utils(40): scandir(string[111] C:\Users\Administrator\Documents\2.survival\plugins\/ReallyCheat/src/hachkingtoh)
  #2 plugins/ReallyCheat-master/src/hachkingtohach1/reallycheat/listener/PlayerListener(358): hachkingtohach1\reallycheat\utils\Utils::callDirectory(string[14] checks/network, object Closure#243041)
  #3 plugins/ReallyCheat-master/src/hachkingtohach1/reallycheat/listener/PlayerListener(263): hachkingtohach1\reallycheat\listener\PlayerListener->checkJustEvent(object pocketmine\event\player\PlayerPreLoginEvent#243044)
  #4 pmsrc/src/event/RegisteredListener(60): hachkingtohach1\reallycheat\listener\PlayerListener->onPlayerPreLogin(object pocketmine\event\player\PlayerPreLoginEvent#243044)
  #5 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerPreLoginEvent#243044)
  #6 pmsrc/src/network/mcpe/handler/LoginPacketHandler(136): pocketmine\event\Event->call()
  #7 pmsrc/vendor/pocketmine/bedrock-protocol/src/LoginPacket(105): pocketmine\network\mcpe\handler\LoginPacketHandler->handleLogin(object pocketmine\network\mcpe\protocol\LoginPacket#242999)
  #8 pmsrc/src/network/mcpe/NetworkSession(388): pocketmine\network\mcpe\protocol\LoginPacket->handle(object pocketmine\network\mcpe\handler\LoginPacketHandler#242992)
  #9 pmsrc/src/network/mcpe/NetworkSession(351): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\LoginPacket#242999, string[31802] ............{"chain":["eyJ4NXUiOiJNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRUpTN)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7411] .].r.Hv..?..P...@.H......IaJ..pT``.$.R.@../.9.z./..ob....^T...u....D\d.=wL......)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[7412] ..].r.Hv..?..P...@.H......IaJ..pT``.$.R.@../.9.z./..ob....^T...u....D\d.=wL.....)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#100173)
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1660607116.8375)
  #16 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[44] C:\Users\Administrator\Documents\2.survival\, string[52] C:\Users\Administrator\Documents\2.survival\plugins\)
  #18 pmsrc/src/PocketMine(327): pocketmine\server()
  #19 pmsrc(11): require(string[88] phar://C:/Users/Administrator/Documents/2.survival/PocketMine-MP.phar/src/Pocket)
--- End of exception information ---
[04:15:16.920] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[04:15:16.935] [Server thread/EMERGENCY]: Please upload the "C:/Users/Administrator/Documents/2.survival/crashdumps/Tue_Aug_16-04.15.16-+0430_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[04:15:16.935] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by Alnezis** [comment]
I had the same problem.
Rename the plugin folder from "ReallyCheat-master" to "ReallyCheat".  This will fix it.

**Comment by UnknownNull** [comment]
wtf
new bug (killaura) im tap to slapper in server next server crash...

**Comment by Alnezis** [comment]
Most likely, your new problem is related to a conflict of Player classes in your plugins. I discovered it myself, since one of my plugins overrides the Player class. A crash occurs when any entities are damaged.
The use of "PlayerCreationEvent" by different plugins is to blame for everything.
We have already written about the possible occurrence of this problem: https://github.com/hachkingtohach1/ReallyCheat/issues/5
