### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DaDevGuy** [hachkingtohach1/ReallyCheat#2]
ErrorException: "scandir(/home/container/plugins//ReallyCheat/src/hachkingtohach1/reallycheat/checks/badpackets): Failed to open directory: No such file or directory" (EXCEPTION) in "plugins/ReallyCheat.phar/src/hachkingtohach1/reallycheat/utils/Utils" at line 51

**Comment by hachkingtohach1** [comment]
You deleted the badpackets file in the plugin's source, right?

**Comment by DaDevGuy** [comment]
i didnt even touched the config
