### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by JoshuaPHYT** [hachkingtohach1/ReallyCheat#6]
[Mon_Jul_25-21.03.25-CEST_2022.log](https://github.com/hachkingtohach1/ReallyCheat/files/9184095/Mon_Jul_25-21.03.25-CEST_2022.log)

**Comment by hachkingtohach1** [comment]
"ReallyCheat/src/hachkingtohach1/reallycheat/checks/network" > Have you deleted this file in the source code of the plugin ?

**Comment by JoshuaPHYT** [comment]
The error got removed the time I deleted

But there is another error but I deleted it. Now There is Error. 
[Sat_Jul_30-17.38.25-CEST_2022.log](https://github.com/hachkingtohach1/ReallyCheat/files/9226824/Sat_Jul_30-17.38.25-CEST_2022.log)
[Sat_Jul_30-17.39.47-CEST_2022.log](https://github.com/hachkingtohach1/ReallyCheat/files/9226825/Sat_Jul_30-17.39.47-CEST_2022.log)
